### ISSUE TITLE
crosspost: vscode issue 

### ISSUE THREAD

**Issue by mavuio** [lachieh/dotfiles#1]
hi!

i created this issue here, just for the purpose of contacting you.

i didn't find a way to post a comment here, as it is locked now:

https://github.com/microsoft/vscode/issues/130832

➜ i just spent 2hrs and made an extension for that:

"Create new Folder from selection"

https://marketplace.visualstudio.com/items?itemName=mavu-io.new-folder-with-selection

maybe you can post the extension there, if people google for that ?

greets from vienna,
manfred

**Comment by lachieh** [comment]
Hi @mavuio, thanks for this extension! It works great!

I don't have access to add more comments on there either but maybe you can ask the member who commented on the issue to link your extension?

Thanks for the note!
